/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sng341.grademanagementsystem;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author uguregecelik
 */
public class CourseFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CourseFrame.class.getName());

    /**
     * Creates new form CourseFrame
     */
    public CourseFrame() {
        initComponents();
        setLocationRelativeTo(null);
        RefreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        Header = new javax.swing.JLabel();
        CIDLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        CreditLabel = new javax.swing.JLabel();
        CID = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Credit = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Menu.background"));
        Panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Header.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Header.setText("Course Management");

        CIDLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        CIDLabel.setText("Course ID:");

        NameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        NameLabel.setText("Name:");

        CreditLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        CreditLabel.setText("Credit:");

        CID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CID.addActionListener(this::CIDActionPerformed);

        Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Credit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AddButton.setText("Add");
        AddButton.addActionListener(this::AddButtonActionPerformed);

        SearchButton.setText("Search");
        SearchButton.addActionListener(this::SearchButtonActionPerformed);

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(this::DeleteButtonActionPerformed);

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(this::UpdateButtonActionPerformed);

        ClearButton.setText("Clear");
        ClearButton.addActionListener(this::ClearButtonActionPerformed);

        Table1.setBackground(javax.swing.UIManager.getDefaults().getColor("MenuItem.underlineSelectionBackground"));
        Table1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Credit"
            }
        ));
        Table1.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(Table1);

        BackButton.setText("Back");
        BackButton.addActionListener(this::BackButtonActionPerformed);

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(Header))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NameLabel)
                                    .addComponent(CIDLabel)
                                    .addComponent(CreditLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CID, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(Name)
                                    .addComponent(Credit))
                                .addGap(58, 58, 58)
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Panel1Layout.createSequentialGroup()
                                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(UpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(BackButton))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Header)
                .addGap(23, 23, 23)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CIDLabel)
                    .addComponent(CID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton)
                    .addComponent(SearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameLabel)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeleteButton)
                        .addComponent(UpdateButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreditLabel)
                    .addComponent(Credit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BackButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CIDActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        try {
            if (CID.getText().isEmpty() || Name.getText().isEmpty() || Credit.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill all required fields! (Course ID, Name, Credit)");
                return;
            }
            
            Integer.parseInt(Credit.getText());

            Class.forName("com.mysql.cj.jdbc.Driver");
            String database = "jdbc:mysql://localhost:3306/GradeManagement?user=root";
            Connection connect = DriverManager.getConnection(database);

            Statement state = connect.createStatement();

            String query = "INSERT INTO Course(CourseID, Name, Credit) VALUES('%s', '%s', '%s')";
            query = String.format(query, CID.getText(), Name.getText(), Credit.getText());

            state.execute(query);

            state.close();
            connect.close();

            JOptionPane.showMessageDialog(null, "Course inserted successfully.");
            RefreshTable();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Credit must be a number!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Coruse could not be inserted.");
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        MainMenuFrame mainMenu = new MainMenuFrame();
        mainMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        try{
            if (CID.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill all required fields! (Course ID)");
                return;
            }
            Class.forName("com.mysql.cj.jdbc.Driver");
            String database = "jdbc:mysql://localhost:3306/GradeManagement?user=root";
            Connection connect = DriverManager.getConnection(database);

            Statement state = connect.createStatement();
            String query = "SELECT * FROM Course WHERE CourseID='%s'";
            query = String.format(query, CID.getText());
            
            ResultSet result = state.executeQuery(query);
            if(result.next()){
                CID.setText(result.getString("CourseID"));
                Name.setText(result.getString("Name"));
                Credit.setText(result.getString("Credit"));
                
                 JOptionPane.showMessageDialog(null, "Course found.");
            } else {
               JOptionPane.showMessageDialog(null,"No course found with this ID!");
           }
            
           state.close();
           connect.close();
           
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Course could not be searched!");
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        try {
            if (CID.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill all required fields! (Course ID)");
                return;
            }

            Class.forName("com.mysql.cj.jdbc.Driver");
            String database = "jdbc:mysql://localhost:3306/GradeManagement?user=root";
            Connection connect = DriverManager.getConnection(database);

            Statement state = connect.createStatement();
            String query = "DELETE FROM Course WHERE CourseID='%s'";
            query = String.format(query, CID.getText());

            int deletedRows = state.executeUpdate(query);

            state.close();
            connect.close();
            
            if (deletedRows > 0) {
                JOptionPane.showMessageDialog(null, "Course deleted successfully.");
                RefreshTable();
            } else {
                JOptionPane.showMessageDialog(null, "No course found with this ID.");
            }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Course could not be deleted.");
    }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        try{
            if (CID.getText().isEmpty() || Name.getText().isEmpty() || Credit.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill all required fields! (Course ID, Name, Credit)");
                return;
            }

            Integer.parseInt(Credit.getText());

            Class.forName("com.mysql.cj.jdbc.Driver");
            String database = "jdbc:mysql://localhost:3306/GradeManagement?user=root";
            Connection connect = DriverManager.getConnection(database);

            Statement state = connect.createStatement();
            String query = "UPDATE Course SET Name='%s', Credit='%s' WHERE CourseID='%s'";
            query = String.format(query, Name.getText(), Credit.getText(), CID.getText());

            int updatedRows = state.executeUpdate(query);

            state.close();
            connect.close();

            if (updatedRows > 0) {
                JOptionPane.showMessageDialog(null, "Course updated successfully.");
                RefreshTable();
            } else {
                JOptionPane.showMessageDialog(null, "No course found with this ID.");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Credit must be a number!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Course could not be updated.");
        } 
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        CID.setText("");
        Name.setText("");
        Credit.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CourseFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField CID;
    private javax.swing.JLabel CIDLabel;
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextField Credit;
    private javax.swing.JLabel CreditLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel Header;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTable Table1;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

private void RefreshTable() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String database = "jdbc:mysql://localhost:3306/GradeManagement?user=root";
            Connection connect = DriverManager.getConnection(database);

            Statement state = connect.createStatement();
            String query = "SELECT * FROM Course";
            ResultSet result = state.executeQuery(query);

            DefaultTableModel dm = (DefaultTableModel) Table1.getModel();

            int rowCount = dm.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                dm.removeRow(i);
            }

            while (result.next()) {
                String id = result.getString("CourseID");
                String name = result.getString("Name");
                String credit = result.getString("Credit");

                Object[] row = {id, name, credit};
                dm.addRow(row);
            }

            state.close();
            connect.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database Error!");
        }
    }
}
