package sng341.grademanagementsystem;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author uguregecelik
 */
public class MainMenuFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuFrame.class.getName());

    /**
     * Creates new form MainMenuFrame
     */
    public MainMenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        StudentsButton = new javax.swing.JButton();
        TeachersButton = new javax.swing.JButton();
        Gradesutton = new javax.swing.JButton();
        CoursesButton = new javax.swing.JButton();
        ReportsButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        FileMenuItem = new javax.swing.JMenu();
        ExitMenuItem = new javax.swing.JMenuItem();
        ManageMenuItem = new javax.swing.JMenu();
        StudentsMenuItem = new javax.swing.JMenuItem();
        TeachersMenuItem = new javax.swing.JMenuItem();
        CoursesMenuItem = new javax.swing.JMenuItem();
        GradesMenuItem = new javax.swing.JMenuItem();
        ReportsMenuItem = new javax.swing.JMenu();
        SearchMenuItem = new javax.swing.JMenuItem();
        BestMenuItem = new javax.swing.JMenuItem();
        CourseWithMenuItem = new javax.swing.JMenuItem();
        TeachersWithoutMenuItem = new javax.swing.JMenuItem();
        StudentAvgMenuItem = new javax.swing.JMenuItem();
        AboutMenuItem = new javax.swing.JMenu();
        HelpMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        Panel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Menu.background"));
        Panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Label1.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorTab.activeBackground"));
        Label1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Label1.setText("Grade Management System");

        StudentsButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        StudentsButton.setText("Students");
        StudentsButton.setPreferredSize(new java.awt.Dimension(150, 50));
        StudentsButton.addActionListener(this::StudentsButtonActionPerformed);

        TeachersButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        TeachersButton.setText("Teachers");
        TeachersButton.setPreferredSize(new java.awt.Dimension(150, 50));
        TeachersButton.addActionListener(this::TeachersButtonActionPerformed);

        Gradesutton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Gradesutton.setText("Grades");
        Gradesutton.setPreferredSize(new java.awt.Dimension(150, 50));
        Gradesutton.addActionListener(this::GradesuttonActionPerformed);

        CoursesButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        CoursesButton.setText("Courses");
        CoursesButton.setPreferredSize(new java.awt.Dimension(150, 50));
        CoursesButton.addActionListener(this::CoursesButtonActionPerformed);

        ReportsButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ReportsButton.setText("Reports");
        ReportsButton.setPreferredSize(new java.awt.Dimension(150, 50));

        ExitButton.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.setPreferredSize(new java.awt.Dimension(50, 15));

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(Label1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StudentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TeachersButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Gradesutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Label1)
                .addGap(18, 18, 18)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeachersButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gradesutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        FileMenuItem.setText("File");

        ExitMenuItem.setText("Exit");
        ExitMenuItem.addActionListener(this::ExitMenuItemActionPerformed);
        FileMenuItem.add(ExitMenuItem);

        MenuBar.add(FileMenuItem);

        ManageMenuItem.setText("Manage");

        StudentsMenuItem.setText("Students");
        StudentsMenuItem.addActionListener(this::StudentsMenuItemActionPerformed);
        ManageMenuItem.add(StudentsMenuItem);

        TeachersMenuItem.setText("Teachers");
        TeachersMenuItem.addActionListener(this::TeachersMenuItemActionPerformed);
        ManageMenuItem.add(TeachersMenuItem);

        CoursesMenuItem.setText("Courses");
        CoursesMenuItem.addActionListener(this::CoursesMenuItemActionPerformed);
        ManageMenuItem.add(CoursesMenuItem);

        GradesMenuItem.setText("Grades");
        GradesMenuItem.addActionListener(this::GradesMenuItemActionPerformed);
        ManageMenuItem.add(GradesMenuItem);

        MenuBar.add(ManageMenuItem);

        ReportsMenuItem.setText("Reports");

        SearchMenuItem.setText("Search Student Grade");
        ReportsMenuItem.add(SearchMenuItem);

        BestMenuItem.setText("Best Student in Course");
        ReportsMenuItem.add(BestMenuItem);

        CourseWithMenuItem.setText("Courses With More Than N Students");
        CourseWithMenuItem.addActionListener(this::CourseWithMenuItemActionPerformed);
        ReportsMenuItem.add(CourseWithMenuItem);

        TeachersWithoutMenuItem.setText("Teachers Without Courses");
        ReportsMenuItem.add(TeachersWithoutMenuItem);

        StudentAvgMenuItem.setText("Student Average Grade");
        ReportsMenuItem.add(StudentAvgMenuItem);

        MenuBar.add(ReportsMenuItem);

        AboutMenuItem.setText("Help");

        HelpMenuItem.setText("Help");
        AboutMenuItem.add(HelpMenuItem);

        MenuBar.add(AboutMenuItem);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsButtonActionPerformed
        StudentFrame studentFrame = new StudentFrame();
        studentFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_StudentsButtonActionPerformed

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    private void StudentsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsMenuItemActionPerformed
        StudentFrame studentFrame = new StudentFrame();
        studentFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_StudentsMenuItemActionPerformed

    private void TeachersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersMenuItemActionPerformed
        TeacherFrame teacherFrame = new TeacherFrame();
        teacherFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_TeachersMenuItemActionPerformed

    private void CoursesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesMenuItemActionPerformed
        CourseFrame courseFrame = new CourseFrame();
        courseFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_CoursesMenuItemActionPerformed

    private void GradesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradesMenuItemActionPerformed
        GradesFrame gradesFrame = new GradesFrame();
        gradesFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_GradesMenuItemActionPerformed

    private void CourseWithMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseWithMenuItemActionPerformed
       
    }//GEN-LAST:event_CourseWithMenuItemActionPerformed

    private void TeachersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersButtonActionPerformed
        TeacherFrame teacherFrame = new TeacherFrame();
        teacherFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_TeachersButtonActionPerformed

    private void CoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesButtonActionPerformed
        CourseFrame courseFrame = new CourseFrame();
        courseFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_CoursesButtonActionPerformed

    private void GradesuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradesuttonActionPerformed
        GradesFrame gradesFrame = new GradesFrame();
        gradesFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_GradesuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenuFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AboutMenuItem;
    private javax.swing.JMenuItem BestMenuItem;
    private javax.swing.JMenuItem CourseWithMenuItem;
    private javax.swing.JButton CoursesButton;
    private javax.swing.JMenuItem CoursesMenuItem;
    private javax.swing.JButton ExitButton;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JMenu FileMenuItem;
    private javax.swing.JMenuItem GradesMenuItem;
    private javax.swing.JButton Gradesutton;
    private javax.swing.JMenuItem HelpMenuItem;
    private javax.swing.JLabel Label1;
    private javax.swing.JMenu ManageMenuItem;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton ReportsButton;
    private javax.swing.JMenu ReportsMenuItem;
    private javax.swing.JMenuItem SearchMenuItem;
    private javax.swing.JMenuItem StudentAvgMenuItem;
    private javax.swing.JButton StudentsButton;
    private javax.swing.JMenuItem StudentsMenuItem;
    private javax.swing.JButton TeachersButton;
    private javax.swing.JMenuItem TeachersMenuItem;
    private javax.swing.JMenuItem TeachersWithoutMenuItem;
    // End of variables declaration//GEN-END:variables
}
