/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sng341.grademanagementsystem;

/**
 *
 * @author uguregecelik
 */
public class ReportsFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportsFrame.class.getName());

    /**
     * Creates new form ReportsFrame
     */
    public ReportsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JLabel();
        MenuLabel = new javax.swing.JLabel();
        SearchStudentGrade = new javax.swing.JButton();
        BestStudentInCourse = new javax.swing.JButton();
        CoursesWithMoreThanNStudents = new javax.swing.JButton();
        TeachersWithoutAnyCourse = new javax.swing.JButton();
        StudentAvgGrade = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Menu.background"));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Header.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Header.setText("Reports");

        MenuLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        MenuLabel.setText("Select to create report:");

        SearchStudentGrade.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SearchStudentGrade.setText("Search Student Grade");
        SearchStudentGrade.addActionListener(this::SearchStudentGradeActionPerformed);

        BestStudentInCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        BestStudentInCourse.setText("Best Student In Course");
        BestStudentInCourse.addActionListener(this::BestStudentInCourseActionPerformed);

        CoursesWithMoreThanNStudents.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        CoursesWithMoreThanNStudents.setText("Courses With More Than N Students");
        CoursesWithMoreThanNStudents.addActionListener(this::CoursesWithMoreThanNStudentsActionPerformed);

        TeachersWithoutAnyCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        TeachersWithoutAnyCourse.setText("Teachers Without Any Courses");
        TeachersWithoutAnyCourse.addActionListener(this::TeachersWithoutAnyCourseActionPerformed);

        StudentAvgGrade.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        StudentAvgGrade.setText("Student Average Grade");
        StudentAvgGrade.addActionListener(this::StudentAvgGradeActionPerformed);

        BackButton.setText("Back");
        BackButton.addActionListener(this::BackButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(Header))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(MenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BestStudentInCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchStudentGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CoursesWithMoreThanNStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TeachersWithoutAnyCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StudentAvgGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(BackButton)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Header)
                .addGap(18, 18, 18)
                .addComponent(MenuLabel)
                .addGap(18, 18, 18)
                .addComponent(SearchStudentGrade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BestStudentInCourse)
                .addGap(12, 12, 12)
                .addComponent(CoursesWithMoreThanNStudents)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TeachersWithoutAnyCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StudentAvgGrade)
                .addGap(18, 18, 18)
                .addComponent(BackButton)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BestStudentInCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BestStudentInCourseActionPerformed
        BestStudentReportFrame frame = new BestStudentReportFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_BestStudentInCourseActionPerformed

    private void CoursesWithMoreThanNStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesWithMoreThanNStudentsActionPerformed
        CoursesWithMoreThanNReportFrame frame = new CoursesWithMoreThanNReportFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_CoursesWithMoreThanNStudentsActionPerformed

    private void TeachersWithoutAnyCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersWithoutAnyCourseActionPerformed
        TeachersWithoutCoursesReportFrame frame = new TeachersWithoutCoursesReportFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_TeachersWithoutAnyCourseActionPerformed

    private void StudentAvgGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentAvgGradeActionPerformed
        StudentAverageGradeFrame frame = new StudentAverageGradeFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_StudentAvgGradeActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        MainMenuFrame mainMenu = new MainMenuFrame();
        mainMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SearchStudentGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchStudentGradeActionPerformed
        SearchGradeReportFrame frame = new SearchGradeReportFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_SearchStudentGradeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportsFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BestStudentInCourse;
    private javax.swing.JButton CoursesWithMoreThanNStudents;
    private javax.swing.JLabel Header;
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JButton SearchStudentGrade;
    private javax.swing.JButton StudentAvgGrade;
    private javax.swing.JButton TeachersWithoutAnyCourse;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
