/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sng341.grademanagementsystem;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author uguregecelik
 */
public class StudentFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentFrame.class.getName());

    /**
     * Creates new form StudentFrame
     */
    public StudentFrame() {
        initComponents();
        setLocationRelativeTo(null);
        RefreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JLabel();
        SIDLabel = new javax.swing.JLabel();
        SID = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        AgeLabel = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 500));

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Menu.background"));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(740, 402));

        Header.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Header.setText("Student Management");

        SIDLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SIDLabel.setText("Student ID:");

        SID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SID.addActionListener(this::SIDActionPerformed);

        NameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        NameLabel.setText("Name:");

        Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AgeLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AgeLabel.setText("Age:");

        Age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Age.addActionListener(this::AgeActionPerformed);

        AddButton.setText("Add");
        AddButton.setSize(new java.awt.Dimension(72, 23));
        AddButton.addActionListener(this::AddButtonActionPerformed);

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(this::UpdateButtonActionPerformed);

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(this::DeleteButtonActionPerformed);

        SearchButton.setText("Search");
        SearchButton.addActionListener(this::SearchButtonActionPerformed);

        ClearButton.setText("Clear");
        ClearButton.setMaximumSize(new java.awt.Dimension(172, 23));
        ClearButton.setMinimumSize(new java.awt.Dimension(172, 23));
        ClearButton.setSize(new java.awt.Dimension(170, 23));
        ClearButton.addActionListener(this::ClearButtonActionPerformed);

        Table2.setBackground(javax.swing.UIManager.getDefaults().getColor("MenuItem.underlineSelectionBackground"));
        Table2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Age"
            }
        ));
        Table2.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(Table2);

        BackButton.setText("Back");
        BackButton.addActionListener(this::BackButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(Header))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BackButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NameLabel)
                                    .addComponent(SIDLabel)
                                    .addComponent(AgeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Name)
                                    .addComponent(Age, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(SID))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(UpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Header)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SIDLabel)
                        .addComponent(SID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UpdateButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton)
                    .addComponent(SearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClearButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AgeLabel)
                        .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BackButton)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SIDActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        try{
            if(SID.getText().isEmpty() || Name.getText().isEmpty() || Age.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Please fill all required fields! (ID, Name, Age)");
                return;
            }
           Integer.parseInt(Age.getText());
            
           Class.forName("com.mysql.cj.jdbc.Driver");
           String database = "jdbc:mysql://localhost:3306/GradeManagement?user=root";
           Connection connect = DriverManager.getConnection(database);
           
           Statement state = connect.createStatement();
           String query = "INSERT INTO Student(ID, Name, Age) VALUES('%s', '%s', '%s')";
           query = String.format(query, SID.getText(), Name.getText(), Age.getText());
           
           state.execute(query);
           
           state.close();
           connect.close();
           
           JOptionPane.showMessageDialog(null, "Student inserted successfully.");
           RefreshTable();
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Age must be a number!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Student could not be inserted.");
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        SID.setText("");
        Name.setText("");
        Age.setText("");
        RefreshTable();
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        MainMenuFrame mainMenu = new MainMenuFrame();
        mainMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        try{
            if(SID.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Please fill all required fields (Student ID)");
                return;
            }
            
           Class.forName("com.mysql.cj.jdbc.Driver");
           String database = "jdbc:mysql://localhost:3306/GradeManagement?user=root";
           Connection connect = DriverManager.getConnection(database);
           
           Statement state = connect.createStatement();
           String query = "DELETE FROM Student WHERE ID='%s'";
           query = String.format(query, SID.getText());
           
           state.execute(query);
           
           state.close();
           connect.close();
           
           JOptionPane.showMessageDialog(null, "Student deleted sucessfully");
           RefreshTable();
            
        } catch (Exception e){
            e.getStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        try{
            if(SID.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please fill all required fields! (Student ID)");
                return;
            }
            
           Class.forName("com.mysql.cj.jdbc.Driver");
           String database = "jdbc:mysql://localhost:3306/GradeManagement?user=root";
           Connection connect = DriverManager.getConnection(database);
           
           Statement state = connect.createStatement();
           String query = "SELECT * FROM Student WHERE ID='%s'";
           query = String.format(query,SID.getText());
           
           ResultSet result = state.executeQuery(query);
           if(result.next()){
               SID.setText(result.getString("ID"));
               Name.setText(result.getString("Name"));
               Age.setText(result.getString("Age"));
               JOptionPane.showMessageDialog(null, "Student found.");
            } else {
               JOptionPane.showMessageDialog(null,"No student found with this ID!");
           }
           
           state.close();
           connect.close();
            
        } catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Student could not be searched!");
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        try {
            if (SID.getText().isEmpty() || Name.getText().isEmpty() || Age.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill all required fields! (Student ID, Name, Age)");
                return;
            }

            Integer.parseInt(Age.getText());

            Class.forName("com.mysql.cj.jdbc.Driver");
            String database = "jdbc:mysql://localhost:3306/GradeManagement?user=root";
            Connection connect = DriverManager.getConnection(database);

            Statement state = connect.createStatement();

            String query = "UPDATE Student SET Name='%s', Age='%s' WHERE ID='%s'";
            query = String.format(query, Name.getText(), Age.getText(), SID.getText());

            int updatedRows = state.executeUpdate(query);

            state.close();
            connect.close();

            if (updatedRows > 0) {
                JOptionPane.showMessageDialog(null, "Student updated successfully.");
                RefreshTable();
            } else {
                JOptionPane.showMessageDialog(null, "No student found with this ID.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Age must be a number!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Student could not be updated.");
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField Age;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel Header;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField SID;
    private javax.swing.JLabel SIDLabel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTable Table2;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void RefreshTable() {
       try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           String database = "jdbc:mysql://localhost:3306/GradeManagement?user=root";
           Connection connect = DriverManager.getConnection(database);
           
           Statement state = connect.createStatement();
           String query = "SELECT * FROM Student";
           ResultSet result = state.executeQuery(query);
           
           DefaultTableModel dm = (DefaultTableModel) Table2.getModel();
           
           int rowCount = dm.getRowCount();
           for(int i = rowCount-1; i>=0; i--){
               dm.removeRow(i);
           }
           
           while(result.next()){
               String id = result.getString("ID");
               String name = result.getString("Name");
               String age = result.getString("Age");
               
               Object[] row = {id,name,age};
               dm.addRow(row);
           }
           
           state.close();
           connect.close();
           
       }catch (Exception e){
           e.printStackTrace();
           JOptionPane.showMessageDialog(null, "Database Error!");
       }
    }
}
